### ISSUE TITLE
Update meta info

### ISSUE THREAD

**Issue by tangrufus** [ItinerisLtd/tiller-circleci-orb#12]
- [ ] Update description in `/src`
- [ ] Update description in readme
- [ ] Mention https://github.com/ItinerisLtd/tiller-monorepo-circleci-orb in readme
- [ ] Mention file structure in readme
